# Generated by Django 4.0 on 2023-05-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(max_length=100, verbose_name='ФИО')),
                ('User_name', models.CharField(max_length=100, verbose_name='Ник')),
                ('Email', models.EmailField(max_length=100, verbose_name='Почта')),
                ('Phone_number', models.CharField(max_length=100, verbose_name='Телефон')),
                ('Password', models.CharField(max_length=100, verbose_name='Пароль')),
                ('Password_confirmation', models.CharField(max_length=100, verbose_name='Подтверждение')),
                ('Gender', models.BooleanField(default=True, verbose_name='Женский пол')),
                ('Gender_1', models.BooleanField(default=True, verbose_name='Мужской пол')),
            ],
        ),
    ]
